### ISSUE TITLE
Expected `cwd` to be of type `string` but received type `undefined`

### ISSUE THREAD

**Issue by vielhuber** [kevva/dir-glob#14] opened 2019-01-13 21:49 UTC
Hello!

When I run inside my npm scripts the line:

        "css:autoprefix": "postcss --use autoprefixer --output ./_public/bundle.css ./_public/bundle.css",

I get the following error:

![image](https://user-images.githubusercontent.com/3183737/51091055-83277080-1785-11e9-882a-05a45f9ac878.png)

After investigating it seems that process.cmd() is undefined on our production server inside the file dir-glob/index.js.

Anybody has a clue why is that?

**Comment by mustafahlvc** [comment] 2019-01-14 11:54
Hi,

I ve the same issue. when i install packages with npm and run the postcss script, i got the same error.

If i use yarn to install packages it works as expected.

this is from yarn.lock
```
dir-glob@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/dir-glob/-/dir-glob-2.0.0.tgz#0b205d2b6aef98238ca286598a8204d29d0a0034"
  integrity sha512-37qirFDz8cA5fimp9feo43fSuRo2gHwaIn6dXL8Ber1dGwUosDrGZeCCXq57WnIqE4aQ+u3eQZzsk1yOzhdwag==
  dependencies:
    arrify "^1.0.1"
    path-type "^3.0.0"
```

this is from package.lock,json

```
"dir-glob": {
            "version": "2.2.1",
            "resolved": "https://registry.npmjs.org/dir-glob/-/dir-glob-2.2.1.tgz",
            "integrity": "sha512-UN6X6XwRjllabfRhBdkVSo63uurJ8nSvMGrwl94EYVz6g+exhTV+yVSYk5VC/xl3MBFBTtC0J20uFKce4Brrng==",
            "requires": {
                "path-type": "^3.0.0"
            },
```

**Comment by kevva** [comment] 2019-01-14 12:42
Duplicate of #10. Make sure that you've `globby@8.0.2` in your lockfile if you use one.

**Closed as completed by kevva** 2019-01-14 12:42 UTC

**Comment by vielhuber** [comment] 2019-01-16 16:34
``npm install globby@8.0.2``

did it, thanks.
