### ISSUE TITLE
Broken build due to major change from 2.0 to 2.2

### ISSUE THREAD

**Issue by dantran** [kevva/dir-glob#13] opened 2019-01-10 22:42 UTC
we ended up to lock down dir-glob-2.0.0.  Apology for not able to give more info

looks like skytelint 0.9.2 also broken

**Comment by bassplayer7** [comment] 2019-01-11 01:29
I'm not sure what situations arise that cause `(typeof opts.cwd !== 'string')` to be true, but this is causing errors to be thrown at least during a build process we run: https://github.com/kevva/dir-glob/blame/master/index.js#L56.

**Comment by dantran** [comment] 2019-01-11 09:10
related to #10

**Comment by kevva** [comment] 2019-01-11 09:41
Duplicate of #10. This should be fixed, it was an issue in `globby`.

**Closed as completed by kevva** 2019-01-11 09:41 UTC
